#:import utils kivy.utils

<DashboardScreen>:
    BoxLayout:
        orientation : "vertical"
        canvas:
            Color:
                rgba: utils.get_color_from_hex("#0d1727")
            Rectangle:
                size: self.size
                pos: self.pos
    ##-----------------Start of Top bar------------------------#
        BoxLayout:
            orientation: "horizontal"
            size_hint:(1,0.03)
            spacing:"10"

            canvas:
                Color:
                    rgba: utils.get_color_from_hex("#121c2e")
                Rectangle:
                    size: self.size
                    pos : self.pos
            Spacer:
                size_hint:(0.75,1)

            ImageButton:
                id: minimize_btn_id
                source:"icons/minimize.png"
                size_hint: (None,None)
                height: "25dp"
                width: "35dp"
                pos_hint:{"center_y": 0.48}
                on_release:
                    app.minimize()

            ImageButton:
                id: clos_btn_id
                source: "icons/cross.png"
                size_hint: (None,None)
                height: "18dp"
                width: "18dp"
                pos_hint: {"center_y" : 0.45}
                on_release:
                    app.close()
            Spacer:
                size_hint: (0.01,1)

        ##-----------------End of Top bar------------------------#



        Spacer:
            size_hint :(1,0.04)

        BoxLayout:
            orientation: "horizontal"
            size_hint: (1,0.06)
            Spacer:
                size_hint:(0.37,1)
            Label:
                text:"COVID-19 Live"
                font_size:"50sp"
                size_hint:(0.2,1)
                color: utils.get_color_from_hex("#748ca6")
            Spacer:
                size_hint:(0.03,1)
            Image:
                source:"icons/ripple.gif"
                size_hint:(0.1,1)
                anim_delay:0.02

            Spacer:
                size_hint:(0.3,1)



        BoxLayout:
            orientation: "vertical"
            size_hint: (0.98,0.87)
            pos_hint:{"right": 0.99}


            ##-----------------Start of Country Search and Date Row------------------------#
            BoxLayout:
                orientation: "horizontal"
                size_hint : (1,0.1)


                Spacer:
                    size_hint:(0.05,1)
                Label:
                    text: "Enter Location : "
                    size_hint:(0.05,0.4)
                    color: utils.get_color_from_hex("#2b2f43")
                Spacer:

                    size_hint:(0.03,1)

                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25,0.5)

                    TextInput:
                        id:search_location_id
                        hint_text: ""
                        font_size : "15sp"
                        font_name : "barlow-reg"
                        size_hint:(1,0.83)
                        background_color : 0,0,0,0
                        foreground_color : 0.8,0.8,0.8,1
                        multiline: False
                        on_text_validate: app.process_datasearch()

                    BoxLayout:
                        size_hint:(1,0.03)
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#2a2f44")
                            Rectangle:
                                size: self.size
                                pos : self.pos
                    Spacer:
                        size_hint:(1,0.1)

                ImageButton:
                    source:"icons/go.png"
                    size_hint: (0.07,0.4)
                    allow_stretch:True
                    keep_aspect: False
                    on_release:
                        app.process_datasearch()

                Spacer:
                    size_hint:(0.05,1) #0.05,1
                Label:
                    id: error_message_id
                    color: utils.get_color_from_hex("#ff0000")
                    font_size:"25sp"
                    text:""
                    font_name: 'barlow-reg'
                    size_hint:(0.35,1)



                Label:
                    id: date_label_id
                    text: "-------"
                    size_hint: (0.1,0.5)
                    font_size: "15sp"
                    font_name : "barlow-reg"
                    color : utils.get_color_from_hex("#2b2f43")
                Spacer:
                    size_hint:(0.05,1)

              ##-----------------End of Country Search and Date Row------------------------#

            Spacer:
                size_hint: (1,0.05)


                ##-----------------Start of "Confirmed Cases", "Active cases", "Confirmed Deaths" row------------------------#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.425)


                ##--Start of Confrimed Cases Widget------#

                BoxLayout:
                    orientation: "vertical"
                    size_hint:(0.74,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.2)
                        Spacer:
                            size_hint:(1,0.1)
                        Label:
                            text: "Confirmed Cases"
                            size_hint:(1,0.9)
                            font_size : "35sp"
                            color: utils.get_color_from_hex("#47546e")

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.6)

                        Label:
                            id: confirmed_cases_id
                            font_size: "150sp"
                            text : "--,--"
                            font_name: "roboto-medium"
                            color: utils.get_color_from_hex("#8695ad")

                    BoxLayout:
                        orientation: "horizontal"
                        size_hint:(1,0.2)
                        Spacer:
                            size_hint:(0.45,0.6)
                        Image:
                            source:"icons/up.png"
                            size_hint:(0.05,0.4)
                            pos_hint:{"center_y": 0.5}

                        Label:
                            id:confirmed_cases_delta_id
                            text: "--"
                            font_size : "22sp"
                            font_name: "roboto-medium"
                            size_hint:(0.05,0.6)
                            color : utils.get_color_from_hex("#950d0d")
                            pos_hint:{"center_y":0.5}

                        Spacer:
                            size_hint:(0.45,0.6)

                    ##--End of Confrimed Cases Widget------#

                Spacer:
                    size_hint:(0.01,1)

                BoxLayout:
                    orientation: "vertical"
                    size_hint:(0.25,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#0d1727")
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    ##--Start of Confrimed Deaths Widget------#

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.5)
                        spacing: "1"
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos: self.pos
                        Spacer:
                            size_hint:(1,0.1)
                        Label:
                            text: "Confrimed Deaths"
                            font_size : "22sp"
                            font_name: "roboto-medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.1)

                        Label:
                            id: confirmed_deaths_id
                            font_size: "55sp"
                            text: "--"
                            font_name: "roboto-medium"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint: (1,0.5)

                        BoxLayout:
                            orientation: "horizontal"
                            size_hint: (1,0.2)

                            Spacer:
                                size_hint: (0.4,0.6)
                            Image:
                                source: "icons/up.png"
                                size_hint:(0.05,0.4)
                                pos_hint:{"center_y" : 0.5}

                            Label:
                                id: confirmed_deaths_delta_id
                                text: "--"
                                font_size: "22sp"
                                size_hint: (0.2,0.6)
                                font_name: "roboto-medium"
                                color: utils.get_color_from_hex("#950d0d")
                                pos_hint:{"center_y" :0.5}
                            Spacer:
                                size_hint:(0.35,0.6)

                        ##--End of Confrimed Deaths Widget------#


                        ##--Start of Active Cases Widget------#

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.5)
                        canvas:
                            Color:
                                rgba:utils.get_color_from_hex("#121c2e")
                            Rectangle:
                                size: self.size
                                pos : self.pos
                        Spacer:
                            size_hint:(1,0.1)
                        Label:
                            text: "Active Cases"
                            font_size: "24sp"
                            font_name:"roboto-medium"
                            color:utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.1)
                        Label:
                            id: active_cases_id
                            font_name: "roboto-medium"
                            font_size: "55sp"
                            text: "--"
                            color: utils.get_color_from_hex("#47546e")
                            size_hint:(1,0.5)

                        BoxLayout:
                            orientation: "horizontal"
                            size_hint:(1,0.2)

                            Spacer:
                                size_hint:(0.29,0.6)
                            Image:
                                source: "icons/brown_circle.png"
                                size_hint: (0.05,0.4)
                                pos_hint: {"center_y":0.5}
                            Spacer:
                                size_hint:(0.01,0.6)
                            Label:
                                id: critical_cases_id
                                text: "--"
                                font_size: "15sp"
                                font_name: "roboto-medium"
                                color: utils.get_color_from_hex("#854102")
                                pos_hint: {"center_y": 0.5}
                                size_hint: (0.4,0.6)
                            Spacer:
                                size_hint:(0.25,0.6)


                        Spacer:
                            size_hint:(1,0.1)

                        ##--End of Active Cases Widget------#
    ##-----------------End of "Confirmed Cases", "Active cases", "Confirmed Deaths" row------------------------#
            Spacer:
                size_hint: (1,0.025)

            ##-----------------Start of "Recovered Cases", "Graph"row------------------------#

            BoxLayout:
                orientation: "horizontal"
                size_hint : (1,0.3)

                BoxLayout:
                    orientation: "horizontal"
                    size_hint: (0.74,1)
                    id: cases_plot_id
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos




                Spacer:
                    size_hint: (0.01,1)

                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size:self.size
                            pos: self.pos
                    Spacer:
                        size_hint:(1,0.1)

                    Label:
                        text:"Recovered"
                        font_size : "24sp"
                        font_name: "roboto-medium"
                        color : utils.get_color_from_hex("#47546e")
                        size_hint: (1,0.5)
                    Label:
                        id: recovered_cases_id
                        text: "--"
                        font_size: "55sp"
                        font_name: "roboto-medium"
                        color: utils.get_color_from_hex("#47546e")
                        size_hint:(1,0.5)

                    BoxLayout:
                        orientation: "horizontal"
                        size_hint: (1,0.2)

                        Spacer:
                            size_hint:(0.29,0.6)
                        Image:
                            source: "icons/green_circle.png"
                            size_hint: (0.05,0.4)
                            pos_hint: {"center_y" : 0.5}
                        Spacer:
                            size_hint:(0.01,0.2)

                        Label:
                            id: recovery_rate_id
                            text: "--"
                            font_size: "15sp"
                            size_hint: (0.4,0.6)
                            font_name: "roboto-medium"
                            color: utils.get_color_from_hex("#05a379")
                            pos_hint: {"center_y":0.5}
                        Spacer:
                            size_hint:(0.25,0.1)
                    Spacer:
                        size_hint:(1,0.1)

           ##-----------------End of "Recovered Cases", "Graph"row------------------------#

            Spacer:
                size_hint:(1,0.03)
